# Generated by Django 6.1 on 2026-09-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipo_empleado_catalog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.tipoempleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.sucursal'),
        ),
    ]
