# Generated by Django 6.1 on 2026-09-18 20:40

import django.db.models.deletion
from django.db import migrations, models


DIRECT_BOSSES = [
    'Esmeralda Perez Castillo',
    'Maria Victoria Diaz Esparza',
    'Diego Fernando Jimenez Lopez',
    'Uriel Sanchez Lopez',
    'Jesus Cuauhtemoc Nevarez Herrera',
    'Francisco Nevarez Herrera',
    'Ivan Felipe Lozano Gonzalez',
    'Jose Juan Lucas Ojeda',
    'Alfredo Trinidad Benitez Mellado',
    'Mariel del Carmen Bustos Gonzalez',
    'Raul Raymundo Betancourt Lira',
    'Juan Carlos Cruz Alvarado',
    'Monica Valeria Flores Martinez',
    'Hector Fernando Lopez Rodriguez',
    'Carlos David Contreras Ortiz',
    'Angela Martinez Lopez',
    'Martha Delia Orozco Castillo',
    'Carlos Alberto Lopez Raichs',
    'Hector Manuel Lopez Nava',
    'Jessica Hernandez Campos',
    'Arturo Sanchez Corral',
]


def load_direct_bosses(apps, schema_editor):
    JefeDirecto = apps.get_model('core', 'JefeDirecto')
    JefeDirecto.objects.bulk_create([JefeDirecto(nombre=nombre) for nombre in DIRECT_BOSSES])


def clear_previous_boss_links(apps, schema_editor):
    Empleado = apps.get_model('core', 'Empleado')
    Empleado.objects.update(jefe_directo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empleado_tipo_empleado_alter_empleado_fecha_alta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JefeDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jefe directo',
                'verbose_name_plural': 'Jefes directos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(clear_previous_boss_links, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.jefedirecto'),
        ),
        migrations.RunPython(load_direct_bosses, migrations.RunPython.noop),
    ]
